name: docs

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          pip install pip -U
          pip install -e .[dev]

      - run: sphinx-build docs/source docs/build -a -W

      - uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: ./docs/build
