name: staticcheck

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ruff (lint)
        uses: chartboost/ruff-action@v1

      - name: Ruff (format)
        uses: chartboost/ruff-action@v1
        with:
          args: "format --check"

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          pip install pip -U
          pip install -e .[dev]

      - run: mypy

      - run: pyright
